const Router = require('koa-router')
const agents = require('./agents')
const menus = require('./menus')
const cars = require('./cars')
const linkmans = require('./linkmans')
const company = require('./insurcecompany')
const bills = require('./bills')
const chaos = require('./events')
const reviews = require('./reviews')

const router = new Router()
router.use('/agents',agents)
router.use('/menus',menus)
router.use('/cars',cars)
router.use('/linkmans',linkmans)
router.use('/company', company)
router.use('/bills',bills)
router.use('/tools',chaos)
router.use('/reviews',reviews)

module.exports = router.routes()